# argocd/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: next-app
  namespace: argocd
spec:
  project: default
  source:
    # 감시할 깃 repo
    repoURL: https://github.com/woobottle/cloud-infra-study.git
    targetRevision: step6/gitops
    path: helm/next-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true        # Git에서 삭제된 리소스는 클러스터에서도 삭제
      selfHeal: true      # 클러스터 상태가 Git과 다르면 자동 복구
    syncOptions:
      - CreateNamespace=true