# 설정값 (ecr 이미지 URL, 포트, replicas)
# Default values for next-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 3

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: 207295118042.dkr.ecr.ap-northeast-2.amazonaws.com/cloud-infra-lab/next-app
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 9b325abebedabb580f21fd852c1f97758f003646

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  port: 3000

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

name: next-app

# kubectl은 가구를 하나씩 옮기는 것 / kubectl apply -f development.yaml로 배포는 할 수 있음
# helm은 이사 패키지 / deployment, service등 여러 yaml을 통해 배포 가능
# values.yaml 하나로 환경별(dev/prod) 설정 변경
# 버전 관리 & 롤백 (helm rollback)